global.config = require("./config.json")
const express = require("express")
const cors = require("cors")
const gamesController = require("./controllers/games-controller")

const server = express()
server.use(cors())
server.use(express.json())
server.use("/api/", gamesController)
server.listen(3001, ()=>{console.log("Listening...")})